config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'logout' => 'application#logout'

   root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_filter :cas_filter
 
def cas_filter
  RubyCAS::Filter.filter(self)
end

def logout
  	reset_session
  	RubyCAS::Filter.logout(self)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_ticket_form.html.erb
<%= form_for :ticket, :html => {:class => "form-horizontal",:id=>'ticket_box'} do |f| %>
  <div class="form-group">
    <label class="col-sm-2 control-label">First Name<span style="color: #FF0000;" >*</span></label>
    <div class="col-sm-7">
      <%= f.text_field :first_name, :class => "form-control" %> 
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Last Name<span style="color: #FF0000;" >*</span></label>
    <div class="col-sm-7">
      <%= f.text_field :last_name, :class => "form-control" %> 
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-2 control-label">Email<span style="color: #FF0000;" >*</span></label>
    <div class="col-sm-7">
       <%= f.text_field :email, :class => "form-control" %> 
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Phone Number(s)<span style="color: #FF0000;" >*</span></label>
    <div class="col-sm-3">
       <%= f.text_field :office_number, :class => "form-control",:placeholder => 'Office' %> 
    </div>
    <div class="col-sm-4">
       <%= f.text_field :cell_number, :class => "form-control",:placeholder => 'Cell' %> 
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Committee<span style="color: #FF0000;" >*</span></label>
    <div class="col-sm-3">
      <select id="rightValues" name="committee" size="4" multiple>
        <option>Criterion 1</option>
        <option>Criterion 2</option>
        <option>Criterion 3</option>
        <option>Criterion 4</option>
        <option>Criterion 5</option>
        <option>Steering Committee</option>
     </select>
     <span id="committee-alert" style="display:none" class="error">Please select atleast one</span>
     </div>
     <label class="col-sm-1 control-label">Core Component<span style="color: #FF0000;" >*</span></label>
     <div class="col-sm-3">
     <select id="core" name="core_component" size="4" multiple>
        <option>N/A</option>
        <option>1.A.</option>
        <option>1.B.</option>
        <option>1.C.</option>
        <option>1.D.</option>
		<option>2.A.</option>
        <option>2.B.</option>
        <option>2.C.</option>
        <option>2.D.</option>
		<option>2.E.</option>
		<option>3.A.</option>
        <option>3.B.</option>
        <option>3.C.</option>
        <option>3.D.</option>
		<option>3.E.</option>
        <option>4.A.</option>
        <option>4.B.</option>
        <option>4.C.</option>
		<option>5.A.</option>
        <option>5.B.</option>
        <option>5.C.</option>
        <option>5.D.</option>
     </select>
     </div>   
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Description<span style="color: #FF0000;" >*</span></label>
    <div class="col-sm-7">
       <%= f.text_area :description, :class => "form-control" %>
       <span class="help-block">Please provide a brief description of the requested data or information. If known, please note the office or individual in possession of the requested items.</span> 
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Preferred Date<span style="color: #FF0000;" >*</span></label>
    <div class="col-sm-7">
       <%= f.text_field :date, :class => "form-control", :id=> 'datepicker' %> 

    <span class="help-block">Please allow for at least two weeks to fulfill your request.  Once the request is received, we will work with the office accessing the data or information to provide an estimated time of delivery. If an urgent request arises, please note it in the description.</span>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-7">
      <%= f.submit 'Submit', :class => "ticket_save", :onclick=>"return SubmitIfValid();" %>
		<%= button_tag "Reset", type: :reset,  :class => "ticket_save" %>
    </div>
  </div>
<% end %>

<script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });

  $("document").ready(function(){
    $("#ticket_box").validate({     

      rules: {
        "ticket[first_name]":{
          required: true
        },
        "ticket[last_name]":{
          required: true
        },
        "ticket[email]":{
           required: true,
           email: true
        },
        "ticket[office_number]":{
           required: true
        },
        
        "committee":{
           required: true
        },
        "core_component":{
           required: true
        },
        "ticket[date]":{
          required: true
        },
        "ticket[description]":{
          required: true
        },
        "tet":{
          required: true
        }
      },
      messages: {
       "ticket[first_name]":{
        required: 'Please enter first name'
        },
        "ticket[last_name]":{
          required: 'Please enter last name'
        },
        "ticket[email]":{
          required: 'Please enter email',
          email: 'Please enter valid email address'
        },
        "ticket[office_number]":{
          required: 'Please enter atleast one phone number'
        },
        "ticket[cell_number]":{
          required: 'Please enter mobile number'
        },
        "committee":{
          required: 'Please select atleast one committee'
        },
        "core_component":{
          required: 'Please select atleast one core component'
        },
        "ticket[date]":{
          required: 'Please select date'
        },
        "ticket[description]":{
          required: 'Please enter description'
        },
        "tet":{
          required: 'Please enter description'
        }

    }  
  
  }); /*close validations */
  });


 function SubmitIfValid()
{
    if($("#ticket_box").valid()){
     alert('Request has been successfully submitted.'); 
     document.getElementById("ticket_box").reset();
     return false;
    }
}
 
  </script>

  <style>
  .error{
    color:red;
    font-style:italic;
  }
  </style>

app/views/home/index.html.erb
    <br>
    <%= render :partial => 'ticket_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accredition</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
 <div class="container">
    <div class="masthead">
        <h3 id="company-name" class="text-muted">University LOGO</h3>
        <nav>
          <ul class="nav nav-justified">
            <li class="active"><a href="#">HLC Evidence Request Form</a></li>
            <li><%= link_to("Sign Out", logout_path) %></li>
          </ul>
        </nav>
    </div>

     <%= yield %>
  </div> <!-- /container -->
<footer class="footer">
  <h6>© The University of New Mexico, Albuquerque, NM 87131, (505) 277-0111</h6>
  <h6>New Mexico's Flagship University</h6>
</footer>
</body>

</html>